# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_config.ipynb.

# %% auto 0
__all__ = ['download_dir']

# %% ../nbs/01_config.ipynb 3
download_dir = "/home/christoph/Dokumente/Baumhaus/Programmieren/data/data_eu_gas_imports"
