# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_download_gas_data.ipynb.

# %% auto 0
__all__ = ['bone', 'year_month', 'gastracker', 'today', 'url', 'today_fn', 'filename', 'r']

# %% ../nbs/00_download_gas_data.ipynb 4
import requests
import os
import datetime
from sys import exit # so that it works in IPython as well

# %% ../nbs/00_download_gas_data.ipynb 6
bone = "https://www.bruegel.org/sites/default/files/"


# %% ../nbs/00_download_gas_data.ipynb 8
year_month = datetime.datetime.today().strftime('%Y-%m')

# %% ../nbs/00_download_gas_data.ipynb 10
gastracker = "/Gas%20tracker%20"

# %% ../nbs/00_download_gas_data.ipynb 12
today = datetime.datetime.today().strftime('%d.%m.%y')

# %% ../nbs/00_download_gas_data.ipynb 14
url = bone + year_month + gastracker + today + '.zip'

# %% ../nbs/00_download_gas_data.ipynb 16
today_fn = datetime.datetime.today().strftime('%y_%m_%d')
filename = today_fn + "_gastracker.zip"

# %% ../nbs/00_download_gas_data.ipynb 18
#|eval: false
r = requests.head(url)
if r.status_code == 404:
    print(f"Nothing to download. File not updated.")
    exit()

